// Copyright 2021 Tamás Gulácsi.
//
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: timezone.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float32 `protobuf:"fixed32,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lon float32 `protobuf:"fixed32,2,opt,name=Lon,proto3" json:"Lon,omitempty"`
}

func (x *Coord) Reset() {
	*x = Coord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timezone_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coord) ProtoMessage() {}

func (x *Coord) ProtoReflect() protoreflect.Message {
	mi := &file_timezone_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coord.ProtoReflect.Descriptor instead.
func (*Coord) Descriptor() ([]byte, []int) {
	return file_timezone_proto_rawDescGZIP(), []int{0}
}

func (x *Coord) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Coord) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type Polygon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Max    *Coord   `protobuf:"bytes,1,opt,name=Max,proto3" json:"Max,omitempty"`
	Min    *Coord   `protobuf:"bytes,2,opt,name=Min,proto3" json:"Min,omitempty"`
	Coords []*Coord `protobuf:"bytes,4,rep,name=Coords,proto3" json:"Coords,omitempty"`
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timezone_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_timezone_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_timezone_proto_rawDescGZIP(), []int{1}
}

func (x *Polygon) GetMax() *Coord {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *Polygon) GetMin() *Coord {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *Polygon) GetCoords() []*Coord {
	if x != nil {
		return x.Coords
	}
	return nil
}

type PolygonIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Tzid string `protobuf:"bytes,2,opt,name=Tzid,proto3" json:"Tzid,omitempty"`
	Max  *Coord `protobuf:"bytes,3,opt,name=Max,proto3" json:"Max,omitempty"`
	Min  *Coord `protobuf:"bytes,4,opt,name=Min,proto3" json:"Min,omitempty"`
}

func (x *PolygonIndex) Reset() {
	*x = PolygonIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timezone_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolygonIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolygonIndex) ProtoMessage() {}

func (x *PolygonIndex) ProtoReflect() protoreflect.Message {
	mi := &file_timezone_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolygonIndex.ProtoReflect.Descriptor instead.
func (*PolygonIndex) Descriptor() ([]byte, []int) {
	return file_timezone_proto_rawDescGZIP(), []int{2}
}

func (x *PolygonIndex) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PolygonIndex) GetTzid() string {
	if x != nil {
		return x.Tzid
	}
	return ""
}

func (x *PolygonIndex) GetMax() *Coord {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *PolygonIndex) GetMin() *Coord {
	if x != nil {
		return x.Min
	}
	return nil
}

var File_timezone_proto protoreflect.FileDescriptor

var file_timezone_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2b, 0x0a, 0x05, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4c,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x4c, 0x6f, 0x6e, 0x22, 0x5d, 0x0a,
	0x07, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x03, 0x4d,
	0x61, 0x78, 0x12, 0x18, 0x0a, 0x03, 0x4d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x03, 0x4d, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x06,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x66, 0x0a, 0x0c,
	0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x7a, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x7a, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x03, 0x4d, 0x61, 0x78, 0x12, 0x18, 0x0a, 0x03, 0x4d, 0x69,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52,
	0x03, 0x4d, 0x69, 0x6e, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x65, 0x76, 0x61, 0x6e, 0x6f, 0x62, 0x65, 0x72, 0x68, 0x6f, 0x6c, 0x73, 0x74,
	0x65, 0x72, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timezone_proto_rawDescOnce sync.Once
	file_timezone_proto_rawDescData = file_timezone_proto_rawDesc
)

func file_timezone_proto_rawDescGZIP() []byte {
	file_timezone_proto_rawDescOnce.Do(func() {
		file_timezone_proto_rawDescData = protoimpl.X.CompressGZIP(file_timezone_proto_rawDescData)
	})
	return file_timezone_proto_rawDescData
}

var file_timezone_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_timezone_proto_goTypes = []interface{}{
	(*Coord)(nil),        // 0: Coord
	(*Polygon)(nil),      // 1: Polygon
	(*PolygonIndex)(nil), // 2: PolygonIndex
}
var file_timezone_proto_depIdxs = []int32{
	0, // 0: Polygon.Max:type_name -> Coord
	0, // 1: Polygon.Min:type_name -> Coord
	0, // 2: Polygon.Coords:type_name -> Coord
	0, // 3: PolygonIndex.Max:type_name -> Coord
	0, // 4: PolygonIndex.Min:type_name -> Coord
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_timezone_proto_init() }
func file_timezone_proto_init() {
	if File_timezone_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timezone_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timezone_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Polygon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timezone_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolygonIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timezone_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_timezone_proto_goTypes,
		DependencyIndexes: file_timezone_proto_depIdxs,
		MessageInfos:      file_timezone_proto_msgTypes,
	}.Build()
	File_timezone_proto = out.File
	file_timezone_proto_rawDesc = nil
	file_timezone_proto_goTypes = nil
	file_timezone_proto_depIdxs = nil
}
